### ISSUE TITLE
Error on make install

### ISSUE THREAD

**Issue by NBSDEVApp** [camspiers/dotfiles#5]
Hi, I have an error with the make install, and the  ubersicht don't show the space on left.

`~/.dotfiles master❯ make install
stow --restow --ignore ".DS_Store" --target="/Users/nbs" --dir="/Users/nbs/.dotfiles" files
BUG in find_stowed_path? Absolute/relative mismatch between Stow dir .dotfiles and path /Volumes/GoogleDrive at /usr/local/Cellar/stow/2.3.1//Library/Perl/5.18/Stow.pm line 966, <DATA> line `22.`

Thanks

**Comment by camspiers** [comment]
There are probably some differences in expectation between where you are attempting to install it from or to, and the installer. However, I don't really want to support the installer in the sense that I encourage others to install it. dotfiles are really meant to be shaped to be your own and I highly discourage installing other peoples, but instead borrowing things from other people. Regarding ubersicht, I don't actually use it any more, because I found that it had significant performance problems.
